# Generated by Django 5.1.5 on 2025-02-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('anio', models.IntegerField()),
                ('creador', models.IntegerField(help_text='Duración en minutos')),
                ('tipo', models.IntegerField()),
            ],
        ),
    ]
