# Generated by Django 5.1.5 on 2025-02-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='creador',
            field=models.CharField(help_text='Nombre del creador', max_length=200),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='tipo',
            field=models.CharField(help_text='Tipo de videojugo', max_length=200),
        ),
    ]
